# mu_config.yaml
sc_input: "../../../../unit-test/test_sc_data.rds"
sp_input: "../../../../unit-test/test_sp_data.rds"
sp_input_rds: "../../../../unit-test/test_sp_data_rds.rds"

gpu: false
cuda_device: 0

rootdir: "/home/abderahim"
output_dir: "."

sampleID: "none"
epoch_build: "10"
epoch_fit: "10"
annot: "subclass"
deconv_args:
  cell2location:
    build: ""
    fit: ""

runID_props: "_001"
output: "res"