# my_config.yaml

# gpu: true
cuda_device: 0

sampleID: "none"
epoch_build: "3"
epoch_fit: "3"
annot: "subclass"
deconv_args:
  cell2location:
    build: ""
    fit: ""

runID_props: "_001"
output: "res"